apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-snmi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-snmi
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-snmi
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-snmi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-snmi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-kosj-tenant/appstudio/dc-metro-map-snmi@sha256:e30f48d199e32c1ced64c289d6bd5c1e71fe93955d015f6fd3cbe79ba92277ae
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
