apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-snmi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-kosj-tenant/appstudio/dc-metro-map-snmi@sha256:e30f48d199e32c1ced64c289d6bd5c1e71fe93955d015f6fd3cbe79ba92277ae
        name: my-nodejs
        resources: {}
status: {}
